#' Creates a plottable data frame from a drug record
#' @param drugRec A drug record
#' @export
createDrugDF <- function(drugRec){

  drugDF <- as.data.frame(t(as.data.frame(drugRec, col.names = c(seq(1:length(drugRec))))))
  drugDF[1,]$V1 <- 0

  #Assign each individual drug an occurrence period of roughly one day
  drugDF$t_start <- cumsum(drugDF$V1)
  drugDF$regimen <- "No"
  drugDF$index <- c(1:length(drugDF$V1))

  #Assign each block a y-height
  drugDF$ymin <- -0.5
  drugDF$ymax <- 0.5
  j <- 0

  for(i in unique(drugDF$V2)){
    drugDF[drugDF$V2 == i,]$ymin <- drugDF[drugDF$V2 == i,]$ymin + (j*1.25)
    drugDF[drugDF$V2 == i,]$ymax <- drugDF[drugDF$V2 == i,]$ymax + (j*1.25)
    j = j + 1
  }

  colnames(drugDF) <- c("t_gap","component","t_start","regimen","index","ymin","ymax")

  drugDF$t_start <- as.numeric(drugDF$t_start)
  drugDF$t_end <- as.numeric(drugDF$t_start+0.9)
  drugDF$ymin <- as.numeric(drugDF$ymin)
  drugDF$ymax <- as.numeric(drugDF$ymax)

  return(drugDF)

}

#' Combines and removes overlapping regimens from an alignment output
#'
#' @param output An output dataframe created by align()
#' @param drugRec A drug record
#' @param drugDF A drugDF object generated by createDrugDF()
#' @param regimenCombine Allowed days between same regimen before being combined
#' @export
combineAndRemoveOverlaps <- function(output, drugRec, drugDF, regimenCombine) {

  outputDF <- output %>%
    dplyr::filter(.data$Score != "") %>%
    dplyr::select(.data$regName, .data$Score,
                  .data$drugRec_Start, .data$drugRec_End,
                  .data$adjustedS, .data$totAlign)

  regCount <- output[is.na(output$adjustedS),]

  regCount <- regCount %>%
    dplyr::rowwise() %>%
    dplyr::mutate(compNo = length(unique(gsub("[0-9]*\\.","",unlist(strsplit(.data$Regimen,";|~")))))) %>%
    dplyr::select(.data$regName, .data$compNo)

  regCount <- regCount[!duplicated(paste(regCount$regName, regCount$compNo)),]

  outputDF$drugRec_Start <- as.numeric(outputDF$drugRec_Start)
  outputDF$drugRec_End <- as.numeric(outputDF$drugRec_End)
  outputDF$totAlign <- as.numeric(outputDF$totAlign)

  outputDF <- outputDF %>%
    dplyr::arrange(.data$drugRec_Start)

  #outputDF$drugRec_Start <- outputDF$drugRec_Start + 1
  #outputDF$drugRec_End <- outputDF$drugRec_End + 1

  if(min(outputDF$drugRec_Start) <= 0){
    outputDF[outputDF$drugRec_Start <= 0,]$drugRec_Start <- 1
  }

  #if(max(outputDF$drugRec_End) > max(drugDF$index)){
  #  outputDF[outputDF$drugRec_End > max(drugDF$index),]$drugRec_End <- max(drugDF$index)
  #}

  outputDF$t_start <- drugDF[outputDF$drugRec_Start,]$t_start
  outputDF$t_end <- drugDF[outputDF$drugRec_End,]$t_start

  outputDF <- outputDF[order(outputDF$t_start, decreasing = F),]
  outputDF$index <- c(1:length(outputDF$drugRec_Start))
  toRemove <- c()

  #Overlap removal
  for(i in c(1:max(outputDF$index))){
    for(j in c(i:max(outputDF$index))){
      if(outputDF[i,]$regName != outputDF[j,]$regName) {
        if(outputDF[i,]$drugRec_Start <= outputDF[j,]$drugRec_End &
           outputDF[i,]$drugRec_End >= outputDF[j,]$drugRec_Start){
          if(!(i %in% toRemove) & !(j %in% toRemove)){
            sel <- outputDF[c(i,j),]

            i_score <- sel[sel$index==i,]$adjustedS
            j_score <- sel[sel$index==j,]$adjustedS

            if(i_score == j_score){
              toRemove <- toRemove
            } else {
              toRemove <- c(toRemove,sel[sel$adjustedS == min(sel$adjustedS),]$index)
            }
          }
        }
      }
    }
  }

  if(length(toRemove) > 0){
    outputDF <- outputDF[-toRemove,] %>%
      dplyr::arrange(.data$drugRec_Start)
  } else {
    outputDF <- outputDF %>%
      dplyr::arrange(.data$t_start)
  }

  # SECOND overlap removal - removing low component high soring regimens

  outputDF <- merge(outputDF,regCount,by = "regName")

  toRemove <- c()

  for(i in c(1:dim(outputDF)[1])){
    for(j in c(i:dim(outputDF)[1])) {
      if(i != j){
        if(outputDF[i,]$t_start < outputDF[j,]$t_end & outputDF[i,]$t_end > outputDF[j,]$t_start){
          mostComps <- max(outputDF[c(i,j),]$compNo)
          toRemove <- c(toRemove,c(i,j)[outputDF[c(i,j),]$compNo < mostComps])

          #if(outputDF[i,]$compNo == outputDF[j,]$compNo){
          #  toRemove <- c(toRemove,c(i,j)[grep(" RT",outputDF[c(i,j),]$regName)])
          #}
        }
      }
    }
  }

  toRemove <- unique(toRemove)

  if(length(toRemove) > 0){
    outputDF <- outputDF[-toRemove,] %>% dplyr::arrange(.data$t_start)
  } else {
    outputDF <- outputDF %>% dplyr::arrange(.data$t_start)
  }

  #Final overlap removal - sub-regimens
  toRemove <- c()

  for(i in c(1:dim(outputDF)[1])){
    for(j in c(i:dim(outputDF)[1])) {
      if(i != j){
        if(outputDF[i,]$regName == outputDF[j,]$regName){
          if(outputDF[i,]$t_start <= outputDF[j,]$t_end & outputDF[j,]$t_start <= outputDF[i,]$t_end){

            highScore <- max(outputDF[c(i,j),]$adjustedS)

            toRemove <- c(toRemove,c(i,j)[outputDF[c(i,j),]$adjustedS < highScore])

          }
        }
      }
    }
  }

  toRemove <- unique(toRemove)

  if(length(toRemove) > 0){
    outputDF <- outputDF[-toRemove,] %>% dplyr::arrange(.data$t_start)
  } else {
    outputDF <- outputDF %>% dplyr::arrange(.data$t_start)
  }

  # Regimen Combine - step 1 - overall combine

  outputDF$Score <- as.numeric(outputDF$Score)
  outputDF$index <- c(1:length(outputDF$drugRec_Start))

  output_Combine_All <- outputDF[0,]

  for(regimenCombi in unique(outputDF$regName)){
    outputTemp <- outputDF[outputDF$regName==regimenCombi,]
    outputTemp <- outputTemp %>%
      dplyr::mutate(prev_end = ifelse(.data$regName ==
                                        dplyr::lag(.data$regName),
                                      dplyr::lag(.data$t_end), 0))
    outputTemp[1,11] <- 0

    outputTemp <- outputTemp %>%
      dplyr::mutate(overlap = outputTemp$t_start <= outputTemp$prev_end+regimenCombine)

    outputTemp$combiIndex <- cumsum(c(0,as.numeric(outputTemp$overlap==FALSE)))[-1]

    output_summ_all <- outputTemp[0,]

    for(index in unique(outputTemp$combiIndex)) {

      outputTemp$adjustedS <- as.numeric(outputTemp$adjustedS)

      outputTemp_toSummarise <- outputTemp[outputTemp$combiIndex == index,] %>%
        dplyr::summarise(regName = unique(.data$regName),
                         Score = mean(.data$Score),
                         drugRec_Start = min(.data$drugRec_Start),
                         drugRec_End = max(.data$drugRec_End),
                         adjustedS = mean(.data$adjustedS),
                         t_start = min(.data$t_start),
                         t_end = max(.data$t_end),
                         totAlign = sum(.data$totAlign))

      output_summ_all <- rbind(output_summ_all,outputTemp_toSummarise)

    }

    output_Combine_All <- rbind(output_Combine_All,output_summ_all)

  }

  outputDF <- output_Combine_All %>%
    dplyr::arrange(.data$t_start)

  return(outputDF)

}

#' Plots, or returns a plot, displaying a full alignment output
#'
#' @param output An output dataframe created by align()
#' @param fontSize The desired font size of the text
#' @param regimenCombine Allowed number of days between two instances of the same regimen before
#' @param returnDat A toggle to also return a processed data object
#' those two instances are combined
#' @return regPlot - A ggplot object
#' @export
plotOutput <- function(output,
                       fontSize = 2.5,
                       regimenCombine = 28,
                       returnDat = F){

  eb <- ggplot2::element_blank()

  drugRec <- encode(output[is.na(output$Score)|output$Score=="",][1,]$DrugRecord)

  output <- output %>%
    dplyr::distinct()

  drugDF <- createDrugDF(drugRec)
  outputDF <- combineAndRemoveOverlaps(output, drugRec, drugDF, regimenCombine)

  outputDF$regimen <- "Yes"

  plotOutput <- outputDF %>%
    dplyr::select(.data$t_start,
                  .data$t_end,
                  .data$regName,
                  .data$regimen,
                  .data$adjustedS)

  plotDrug <- drugDF %>%
    dplyr::select(.data$t_start,
                  .data$t_end,
                  .data$component,
                  .data$regimen)

  plotDrug$adjustedS <- "-1"
  colnames(plotOutput)[3] <- "component"

  plotDrug <- plotDrug %>%
    dplyr::mutate(component = strsplit(.data$component,"~")) %>%
    tidyr::unnest(.data$component)

  plot <- rbind(plotDrug,plotOutput)

  ord <- unique(plot[order(plot$regimen,plot$t_start),]$component)

  plot$component <- factor(plot$component, levels = ord)

  breaks <- seq(-14, max(plot$t_end)+5, 1)
  tickLabels <- as.character(breaks)
  tickLabels[!(breaks %% 28 == 0)] <- ''

  overlapLines <- as.data.frame(matrix(ncol = 5))
  overlapT <- plot[plot$regimen == "Yes",]
  j <- 1

  if(dim(overlapT)[1] > 1){
    for(i in c(1:(dim(overlapT)[1]-1))){
      if(overlapT[i,]$component==overlapT[i+1,]$component){
        overlapLines[j,] <- c(as.numeric(overlapT[i,]$t_end),
                              as.numeric(overlapT[i+1,]$t_start),
                              as.character(overlapT[i,]$component),
                              "Line","0")
        j <- j + 1
      }
    }
  }

  colnames(overlapLines) <- colnames(plot)
  overlapLines$t_start <- as.numeric(overlapLines$t_start)
  overlapLines$t_end <- as.numeric(overlapLines$t_end)
  overlapLines$component <- factor(overlapLines$component, levels = ord)

  plot[plot$regimen=="Yes",]$t_start <- plot[plot$regimen=="Yes",]$t_start - 2
  plot[plot$regimen=="Yes",]$t_end <- plot[plot$regimen=="Yes",]$t_end + 2

  p1 <- ggplot2::ggplot(plot, ggplot2::aes(x = .data$t_start)) +
    ggchicklet::geom_rrect(data = plot[plot$regimen=="Yes",],
                           ggplot2::aes(ymin = as.numeric(.data$component)-0.3,
                                        ymax = as.numeric(.data$component)+0.3,
                                        xmin = .data$t_start,
                                        xmax = .data$t_end, fill = .data$component)) +
    ggplot2::geom_text(size = 3.5,
                       data = plot[plot$regimen=="Yes",],
                       ggplot2::aes(x = (.data$t_start+.data$t_end)/2,
                                    y = as.numeric(.data$component)+0.5,
                                    label=paste("Score: ",round(as.numeric(.data$adjustedS),3)))) +
    ggplot2::geom_point(data = plot[plot$regimen=="No",], size = 3,
                        ggplot2::aes(x= .data$t_start,y= as.numeric(.data$component),
                                     fill = .data$component), shape = 21) +
    ggplot2::scale_y_continuous(labels = stringi::stri_trans_totitle(ord), breaks = seq(1,length(ord))) +
    ggplot2::scale_x_continuous(breaks = seq(0,max(plot$t_end),28)) +
    ggplot2::theme(panel.background = ggplot2::element_blank(),
                   panel.grid.major = ggplot2::element_line(colour = "grey95"),
                   legend.position = "none") +
    ggplot2::xlab("") + ggplot2::ylab("") +
    ggplot2::geom_segment(data = overlapLines, ggplot2::aes(y = as.numeric(.data$component),
                                                            yend = as.numeric(.data$component),
                                                            x = .data$t_start,
                                                            xend = .data$t_end,
                                                            colour = .data$component),
                          linetype = 2, lwd = 1) +
    ggplot2::scale_fill_viridis_d(drop=F) +
    ggplot2::scale_color_viridis_d(drop=F) +
    ggplot2::geom_hline(linetype = 3,
                        yintercept = table(plot[!duplicated(plot$component),]$regimen == "No")[2]+0.5)

  if(returnDat == TRUE){
    plotOutput$personID <- unique(output$personID)
    return(plotOutput)
  } else {
    return(p1)
  }
}


